version: "3"

services:
  db:
    env_file:
      - .env
    image: postgres:9.6-alpine
    container_name: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  server:
    command: "diesel migration run --database-url=${DATABASE_URL}"
    restart: on-failure
    depends_on:
      - db
    build: identified_server
    env_file:
      - .env
    ports:
      - "8000:8000"
  web:
    restart: on-failure
    depends_on:
      - db
    build: identified_web

volumes:
  dbdata:
